-- vim.api.nvim_create_autocmd('BufWritePre', {
-- 	group = vim.api.nvim_create_augroup('trim_whitespaces', { clear = true }),
-- 	desc = 'Trim trailing white spaces',
-- 	pattern = '<buffer>',
-- 	callback = require('core.utils').trim_trailing_whitespaces
-- })
